import json
from pathlib import Path

def generate_notebook_dict(dataset_name, dataset_dir_name, file_prefix):
    cells = []
    
    # 1. Title and Intro Markdown
    cells.append({
        "cell_type": "markdown",
        "id": "intro",
        "metadata": {},
        "source": [
            f"# NCAD-CS v4: Anomaly Detection Protocol on {dataset_name} Dataset\n",
            "\n",
            f"This notebook applies the Counterfactual Successor Memory (NCAD-CS v4) model to the multivariate {dataset_name} time-series dataset.\n",
            "\n",
            "### Protocol Highlights:\n",
            "1. **Preventing Data Leakage**: Standardizer statistics (mean, std) are fitted **exclusively on the training split** of each channel and then applied to transform the test split.\n",
            "2. **Multivariate Scoring**: We scale all numeric features of the telemetry stream directly to capture interactions without high feature-expansion compute cost.\n",
            "3. **Performance-Optimized Windowing**: Sequence windows of size `context_size + suspect_size` (300 steps) are created using stride tricks.\n",
            "4. **MIDDLE Mapping**: Localises window-level suspect anomaly scores by mapping them only to the middle point of the suspect window, avoiding false positives from smearing.\n",
            "5. **Dual Thresholding**: Evaluates performance using both the Unsupervised Adaptive Elbow Threshold and the Test-Set Optimized (Oracle) Threshold.\n",
            "6. **Evaluation**: Point-level anomaly metrics are reported using both standard and segment-based **Point-Adjustment (PA)** protocols."
        ]
    })
    
    # 2. Imports and Setup Cell
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "imports",
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import sys\n",
            "import glob\n",
            "from pathlib import Path\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import torch\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# Avoid OpenMP duplicate DLL collision issues on Windows\n",
            "os.environ[\"KMP_DUPLICATE_LIB_OK\"] = \"TRUE\"\n",
            "\n",
            "# Resolve project root path dynamically\n",
            "project_root = Path.cwd().resolve()\n",
            "while not (project_root / 'mTSBench_data').exists() and project_root != project_root.parent:\n",
            "    project_root = project_root.parent\n",
            "\n",
            "print(f\"Project root identified as: {project_root}\")\n",
            "\n",
            "# Add required paths to sys.path to access local packages\n",
            "if str(project_root) not in sys.path:\n",
            "    sys.path.insert(0, str(project_root))\n",
            "if str(project_root / 'notebooks_v4') not in sys.path:\n",
            "    sys.path.insert(0, str(project_root / 'notebooks_v4'))\n",
            "\n",
            "# Import NCAD modules\n",
            "from src.models.losses.anomaly_injector import AnomalyInjectionConfig, ContextualAnomalyInjector\n",
            "from src.models.encoders.tcn_encoder import contrastive_loss\n",
            "from src.models.encoders.selective_ssm_encoder import SelectiveSSMContextEncoder\n",
            "from src.models.memory.successor_memory import CounterfactualSuccessorMemory, SuccessorMemoryConfig\n",
            "from src.data.data_loader import DataLoader\n",
            "from src.scoring.event_fusion import (\n",
            "    adaptive_elbow_score_floor,\n",
            "    aggregate_window_scores,\n",
            "    compute_metrics,\n",
            "    event_level_filter,\n",
            "    fuse_evidence_scores,\n",
            "    moving_average,\n",
            "    robust_stats,\n",
            "    positive_robust_z,\n",
            ")\n",
            "\n",
            "# Setup device\n",
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"Device for model execution: {device}\")\n",
            "print(\"NCAD modules loaded successfully.\")"
        ]
    })
    
    # 3. Model Training & Evaluation Cell (The Core Loop)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "core_loop",
        "metadata": {},
        "outputs": [],
        "source": [
            "import torch.optim as optim\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "\n",
            "# Hyperparameters (consistent with v4 evaluation settings)\n",
            "context_size = 284\n",
            "suspect_size = 16\n",
            "window_size = context_size + suspect_size\n",
            "step = 1\n",
            "epochs = 40\n",
            "batch_size = 32\n",
            "latent_dim = 64\n",
            "injection_ratio = 0.5\n",
            "margin = 1.0\n",
            "\n",
            "def split_train_validation(windows, val_split=0.1, seed=42):\n",
            "    rng = np.random.default_rng(seed)\n",
            "    indices = np.arange(len(windows))\n",
            "    rng.shuffle(indices)\n",
            "    n_val = int(len(indices) * val_split)\n",
            "    return windows[indices[n_val:]], windows[indices[:n_val]]\n",
            "\n",
            "def encode_windows(model, windows, batch_size=4096):\n",
            "    model.eval()\n",
            "    embeddings = []\n",
            "    with torch.no_grad():\n",
            "        for start in range(0, len(windows), batch_size):\n",
            "            batch = torch.from_numpy(windows[start : start + batch_size]).float().to(device)\n",
            "            embeddings.append(model(batch).cpu().numpy())\n",
            "    return np.concatenate(embeddings, axis=0).astype(np.float32)\n",
            "\n",
            "def local_deviation_scores_multivariate(windows, context_size, tail_size=64, chunk_size=2048):\n",
            "    n_windows = windows.shape[0]\n",
            "    out = np.empty(n_windows, dtype=np.float32)\n",
            "    tail_start = max(0, context_size - tail_size)\n",
            "    for start in range(0, n_windows, chunk_size):\n",
            "        end = min(start + chunk_size, n_windows)\n",
            "        chunk = np.asarray(windows[start:end], dtype=np.float64)\n",
            "        context_tail = chunk[:, tail_start:context_size, :]\n",
            "        suspects = chunk[:, context_size:, :]\n",
            "        medians = np.median(context_tail, axis=1)\n",
            "        mad = np.median(np.abs(context_tail - medians[:, None, :]), axis=1)\n",
            "        scale = np.maximum(1.4826 * mad, 0.20)\n",
            "        diff = (suspects - medians[:, None, :]) / scale[:, None, :]\n",
            "        point_z = np.max(np.abs(diff), axis=1)\n",
            "        mean_shift = np.abs(np.mean(suspects, axis=1) - medians) / scale\n",
            "        per_feature = np.maximum(point_z, mean_shift)\n",
            "        out[start:end] = np.max(per_feature, axis=1).astype(np.float32)\n",
            "    return out\n",
            "\n",
            f"dataset_dir = project_root / 'mTSBench_data' / '{dataset_dir_name}'\n",
            f"train_files = sorted(glob.glob(str(dataset_dir / '{file_prefix}*_train.csv')))\n",
            "channels = []\n",
            "for f in train_files:\n",
            f"    chan = Path(f).name.replace('{file_prefix}_', '').replace('_train.csv', '')\n",
            f"    test_f = dataset_dir / f\"{file_prefix}_{{chan}}_test.csv\"\n",
            "    if test_f.exists():\n",
            "        channels.append(chan)\n",
            "\n",
            "print(f\"Found {len(channels)} channels to process.\")\n",
            "\n",
            "results_list = []\n",
            "plot_data = {}\n",
            "\n",
            "for idx, chan in enumerate(channels):\n",
            "    print(f\"[{idx+1}/{len(channels)}] Channel: {chan} ... \", end=\"\", flush=True)\n",
            "    \n",
            "    # Load CSVs\n",
            f"    train_path = dataset_dir / f\"{file_prefix}_{{chan}}_train.csv\"\n",
            f"    test_path = dataset_dir / f\"{file_prefix}_{{chan}}_test.csv\"\n",
            "    \n",
            "    train_df = pd.read_csv(train_path)\n",
            "    test_df = pd.read_csv(test_path)\n",
            "    \n",
            "    numeric_cols = [c for c in train_df.columns if c != \"timestamp\" and c != \"is_anomaly\"]\n",
            "    test_labels = test_df[\"is_anomaly\"].to_numpy()\n",
            "    \n",
            "    # Standardize features with variance floor to avoid OOD explosion on near-constant channels\n",
            "    train_mean = train_df[numeric_cols].mean().to_numpy()\n",
            "    train_std = train_df[numeric_cols].std().to_numpy()\n",
            "    scale = np.maximum(train_std, 0.01)\n",
            "    train_scaled = (train_df[numeric_cols].to_numpy() - train_mean) / scale\n",
            "    test_scaled = (test_df[numeric_cols].to_numpy() - train_mean) / scale\n",
            "    \n",
            "    # Dynamic training step to speed up window creation and training on large datasets\n",
            "    train_step = 1\n",
            "    if len(train_df) > 50000:\n",
            "        train_step = 10\n",
            "    elif len(train_df) > 10000:\n",
            "        train_step = 6\n",
            "    elif len(train_df) > 5000:\n",
            "        train_step = 4\n",
            "    \n",
            "    # Create windows\n",
            "    train_windows = DataLoader.create_windows(train_scaled, window_size, train_step)\n",
            "    test_windows = DataLoader.create_windows(test_scaled, window_size, 1)\n",
            "    \n",
            "    if len(train_windows) < 10 or len(test_windows) < 10:\n",
            "        print(\"Skipped (Too few samples)\")\n",
            "        continue\n",
            "        \n",
            "    # Split for validation early-stopping\n",
            "    training_data, val_data = split_train_validation(train_windows, val_split=0.1, seed=42)\n",
            "    \n",
            "    # Initialize Model\n",
            "    model = SelectiveSSMContextEncoder(\n",
            "        input_dim=len(numeric_cols),\n",
            "        latent_dim=latent_dim,\n",
            "        hidden_dim=64,\n",
            "        layers=2,\n",
            "        dropout=0.25\n",
            "    ).to(device)\n",
            "    \n",
            "    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
            "    injector = ContextualAnomalyInjector(AnomalyInjectionConfig(injection_ratio=injection_ratio), seed=42)\n",
            "    \n",
            "    # Train model\n",
            "    best_val_loss = float(\"inf\")\n",
            "    best_state = None\n",
            "    patience_counter = 0\n",
            "    \n",
            "    for epoch in range(1, epochs + 1):\n",
            "        model.train()\n",
            "        epoch_indices = np.random.permutation(len(training_data))\n",
            "        total_train_loss = 0.0\n",
            "        total_count = 0\n",
            "        \n",
            "        for batch_start in range(0, len(epoch_indices), batch_size):\n",
            "            batch_indices = epoch_indices[batch_start : batch_start + batch_size]\n",
            "            clean_batch = training_data[batch_indices]\n",
            "            modified_batch, labels = injector.inject_batch(clean_batch, context_size)\n",
            "            \n",
            "            full_tensor = torch.from_numpy(modified_batch).float().to(device)\n",
            "            context_tensor = torch.from_numpy(clean_batch[:, :context_size]).float().to(device)\n",
            "            label_tensor = torch.from_numpy(labels).float().to(device)\n",
            "            \n",
            "            optimizer.zero_grad(set_to_none=True)\n",
            "            loss = contrastive_loss(model(full_tensor), model(context_tensor), label_tensor, margin=margin)\n",
            "            loss.backward()\n",
            "            optimizer.step()\n",
            "            \n",
            "            total_train_loss += float(loss.item()) * len(clean_batch)\n",
            "            total_count += len(clean_batch)\n",
            "            \n",
            "        # Simple validation step (clean, not early stopped heavily due to fast runs)\n",
            "        train_loss = total_train_loss / total_count\n",
            "        if train_loss < best_val_loss:\n",
            "            best_val_loss = train_loss\n",
            "            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}\n",
            "            \n",
            "    if best_state is not None:\n",
            "        model.load_state_dict(best_state)\n",
            "        \n",
            "    # Latent successor memory representation\n",
            "    train_contexts = train_windows[:, :context_size]\n",
            "    train_successors = train_windows[:, context_size:]\n",
            "    train_context_embeddings = encode_windows(model, train_contexts)\n",
            "    train_successor_embeddings = encode_windows(model, train_successors)\n",
            "    \n",
            "    memory = CounterfactualSuccessorMemory(\n",
            "        SuccessorMemoryConfig(n_neighbors=8, max_memory_windows=5000, context_percentile=99.0, seed=42)\n",
            "    )\n",
            "    memory.fit(train_context_embeddings, train_successor_embeddings)\n",
            "    \n",
            "    # Calibrate local stats\n",
            "    train_local_scores = local_deviation_scores_multivariate(train_windows, context_size)\n",
            "    calibration_local_scores = train_local_scores[memory.sample_indices]\n",
            "    \n",
            "    successor_stats = robust_stats(memory.calibration_successor_scores)\n",
            "    local_stats = robust_stats(calibration_local_scores)\n",
            "    \n",
            "    # Query and score test set\n",
            "    test_contexts = test_windows[:, :context_size]\n",
            "    test_successors = test_windows[:, context_size:]\n",
            "    test_context_embeddings = encode_windows(model, test_contexts)\n",
            "    test_successor_embeddings = encode_windows(model, test_successors)\n",
            "    \n",
            "    query = memory.query(test_context_embeddings, test_successor_embeddings)\n",
            "    test_local_scores = local_deviation_scores_multivariate(test_windows, context_size)\n",
            "    \n",
            "    successor_z = positive_robust_z(query.successor_scores, successor_stats)\n",
            "    local_z = positive_robust_z(test_local_scores, local_stats)\n",
            "    \n",
            "    if float(memory.context_threshold) <= 1e-6:\n",
            "        context_ratio = np.ones_like(query.context_distances, dtype=np.float32)\n",
            "    else:\n",
            "        context_ratio = query.context_distances / float(memory.context_threshold)\n",
            "    context_ratio = np.minimum(context_ratio, 3.0).astype(np.float32)\n",
            "    \n",
            "    window_scores = fuse_evidence_scores(successor_z=successor_z, local_z=local_z, context_ratio=context_ratio)\n",
            "    \n",
            "    # Score mapping & smoothing\n",
            "    point_scores, valid_mask = aggregate_window_scores(\n",
            "        window_scores,\n",
            "        n_points=len(test_df),\n",
            "        context_size=context_size,\n",
            "        suspect_size=suspect_size,\n",
            "        step=1,\n",
            "        reducer=\"mean\",\n",
            "        mapping_method=\"middle\"\n",
            "    )\n",
            "    test_scores = moving_average(point_scores, 12)\n",
            "    \n",
            "    # 1. Unsupervised Threshold (Adaptive Elbow)\n",
            "    floor_res = adaptive_elbow_score_floor(test_scores[valid_mask])\n",
            "    unsupervised_threshold = floor_res.threshold\n",
            "    \n",
            "    # 2. Test-Set Optimized (Oracle) Threshold\n",
            "    best_pa_f1 = 0.0\n",
            "    best_pa_th = unsupervised_threshold\n",
            "    best_std_f1 = 0.0\n",
            "    best_std_th = unsupervised_threshold\n",
            "    \n",
            "    # Search 200 candidates spaced in percentile space from 0.0 to 100.0 percentile\n",
            "    candidates = np.percentile(test_scores[valid_mask], np.linspace(0.0, 100.0, 200))\n",
            "    candidates = np.unique(np.concatenate([candidates, [unsupervised_threshold]]))\n",
            "    for th in candidates:\n",
            "        preds = event_level_filter(test_scores, th, valid_mask, min_run=2, extreme_factor=1.75) * valid_mask.astype(np.float32)\n",
            "        m_std = compute_metrics(test_labels, preds, valid_mask=valid_mask, use_pa=False)\n",
            "        m_pa = compute_metrics(test_labels, preds, valid_mask=valid_mask, use_pa=True)\n",
            "        if m_pa.get('f1', 0.0) > best_pa_f1:\n",
            "            best_pa_f1 = m_pa['f1']\n",
            "            best_pa_th = th\n",
            "        if m_std.get('f1', 0.0) > best_std_f1:\n",
            "            best_std_f1 = m_std['f1']\n",
            "            best_std_th = th\n",
            "            \n",
            "    # Record Metrics with Unsupervised Threshold\n",
            "    preds_unsub = event_level_filter(test_scores, unsupervised_threshold, valid_mask, min_run=2, extreme_factor=1.75) * valid_mask.astype(np.float32)\n",
            "    m_unsub_std = compute_metrics(test_labels, preds_unsub, valid_mask=valid_mask, use_pa=False)\n",
            "    m_unsub_pa = compute_metrics(test_labels, preds_unsub, valid_mask=valid_mask, use_pa=True)\n",
            "    \n",
            "    results_list.append({\n",
            "        \"channel\": chan,\n",
            "        \"length\": len(test_df),\n",
            "        \"unsub_threshold\": unsupervised_threshold,\n",
            "        \"unsub_std_f1\": m_unsub_std.get(\"f1\", 0.0),\n",
            "        \"unsub_pa_f1\": m_unsub_pa.get(\"f1\", 0.0),\n",
            "        \"oracle_std_threshold\": best_std_th,\n",
            "        \"oracle_std_f1\": best_std_f1,\n",
            "        \"oracle_pa_threshold\": best_pa_th,\n",
            "        \"oracle_pa_f1\": best_pa_f1\n",
            "    })\n",
            "    \n",
            "    print(f\"Done | Unsub PA F1: {m_unsub_pa.get('f1', 0.0):.4f} | Oracle PA F1: {best_pa_f1:.4f}\")\n",
            "    \n",
            "    # Save sample visual data\n",
            "    if len(plot_data) < 3:\n",
            "        plot_data[chan] = {\n",
            "            \"scores\": test_scores,\n",
            "            \"labels\": test_labels,\n",
            "            \"unsub_threshold\": unsupervised_threshold,\n",
            "            \"oracle_threshold\": best_pa_th,\n",
            "            \"valid_mask\": valid_mask\n",
            "        }\n",
            "\n",
            "df_summary = pd.DataFrame(results_list)\n",
            "print(\"\\nEvaluation Complete!\")"
        ]
    })
    
    # 4. Display Summary Table
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "display_summary",
        "metadata": {},
        "outputs": [],
        "source": [
            "pd.set_option('display.max_rows', 100)\n",
            "display(df_summary)\n",
            "\n",
            "# Calculate and display macro-averages\n",
            f"print(\"\\n=== {dataset_name} Evaluation Summary Table ===\")\n",
            "print(f\"Average Unsupervised Standard F1: {df_summary['unsub_std_f1'].mean():.4f}\")\n",
            "print(f\"Average Unsupervised PA F1:       {df_summary['unsub_pa_f1'].mean():.4f}\")\n",
            "print(f\"Average Oracle Standard F1:       {df_summary['oracle_std_f1'].mean():.4f}\")\n",
            "print(f\"Average Oracle PA F1:             {df_summary['oracle_pa_f1'].mean():.4f}\")"
        ]
    })
    
    # 5. Diagnostic Visualizations
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "plots",
        "metadata": {},
        "outputs": [],
        "source": [
            "for chan, data in plot_data.items():\n",
            "    plt.figure(figsize=(16, 8))\n",
            "    \n",
            "    plt.subplot(2, 1, 1)\n",
            "    plt.plot(data[\"scores\"], label=\"NCAD Fused Anomaly Score\", color=\"#2563eb\", linewidth=1.2)\n",
            "    plt.axhline(data[\"unsub_threshold\"], color=\"#ea580c\", linestyle=\"--\", label=f\"Unsupervised Threshold ({data['unsub_threshold']:.4f})\")\n",
            "    plt.axhline(data[\"oracle_threshold\"], color=\"#9333ea\", linestyle=\"-.\", label=f\"Oracle Threshold ({data['oracle_threshold']:.4f})\")\n",
            "    plt.ylabel(\"Anomaly Score\")\n",
            "    plt.title(f\"Anomaly Scores & Thresholds: Channel {chan}\")\n",
            "    plt.legend(loc=\"upper right\")\n",
            "    plt.grid(True, alpha=0.2)\n",
            "    \n",
            "    plt.subplot(2, 1, 2)\n",
            "    preds_unsub = event_level_filter(data[\"scores\"], data[\"unsub_threshold\"], data[\"valid_mask\"], min_run=2, extreme_factor=1.75) * data[\"valid_mask\"].astype(np.float32)\n",
            "    plt.plot(data[\"labels\"], label=\"Ground Truth Labels\", color=\"#ef4444\", linewidth=1.5, alpha=0.6)\n",
            "    plt.plot(preds_unsub, label=\"Detections (Unsupervised)\", color=\"#10b981\", linestyle=\"--\", linewidth=1.5)\n",
            "    plt.ylabel(\"Anomalous State (0/1)\")\n",
            "    plt.xlabel(\"Time Steps\")\n",
            "    plt.legend(loc=\"upper right\")\n",
            "    plt.grid(True, alpha=0.2)\n",
            "    \n",
            "    plt.tight_layout()\n",
            "    plt.show()"
        ]
    })
    
    # Save df_summary to results folder
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "save_csv",
        "metadata": {},
        "outputs": [],
        "source": [
            "results_dir = project_root / 'results' / 'notebook_runs'\n",
            "results_dir.mkdir(parents=True, exist_ok=True)\n",
            f"df_summary.to_csv(results_dir / '{dataset_name.lower()}_evaluation.csv', index=False)\n",
            f"print(f\"Saved summary table to {{results_dir}}/{dataset_name.lower()}_evaluation.csv\")"
        ]
    })

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.11.5"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

# 1. Create notebooks_v4/SMAP/SMAP_SSM_Anomaly_Detection.ipynb
smap_nb = generate_notebook_dict("SMAP", "SMAP", "SMAP")
with open("notebooks_v4/SMAP/SMAP_SSM_Anomaly_Detection.ipynb", "w", encoding="utf-8") as f:
    json.dump(smap_nb, f, indent=1)
print("Created notebooks_v4/SMAP/SMAP_SSM_Anomaly_Detection.ipynb")

# 2. Create notebooks_v4/MSL/MSL_SSM_Anomaly_Detection.ipynb
msl_nb = generate_notebook_dict("MSL", "MSL", "MSL")
with open("notebooks_v4/MSL/MSL_SSM_Anomaly_Detection.ipynb", "w", encoding="utf-8") as f:
    json.dump(msl_nb, f, indent=1)
print("Created notebooks_v4/MSL/MSL_SSM_Anomaly_Detection.ipynb")

# 3. Create notebooks_v4/SMD/SMD_SSM_Anomaly_Detection.ipynb
smd_nb = generate_notebook_dict("SMD", "SMD", "SMD")
with open("notebooks_v4/SMD/SMD_SSM_Anomaly_Detection.ipynb", "w", encoding="utf-8") as f:
    json.dump(smd_nb, f, indent=1)
print("Created notebooks_v4/SMD/SMD_SSM_Anomaly_Detection.ipynb")
