"""Models package for NCAD-CS.

Organized into subpackages:
- ``encoders``: temporal sequence encoder backbones (TCN, GAT, SSM)
- ``jepa``: JEPA-family predictive architectures
- ``memory``: counterfactual successor memory and dynamics scorers
- ``losses``: anomaly injection and loss utilities
- ``baselines``: SOTA baseline models for comparison
- ``legacy``: backward-compatibility shims
"""

from src.models.baselines import (
    AnomalyTransformer,
    DCdetector,
    TimesNet,
    TranAD,
)
from src.models.encoders import (
    HybridTCNEncoder,
    MultiScaleTCNEncoder,
    RelationalGATEncoder,
    SelectiveSSMContextEncoder,
    contrastive_loss,
)
from src.models.jepa import (
    PF_JEPA,
    CausalSSMContextEncoder,
    CausalSSMFlowJEPA,
    CosineCycleJEPA,
    CosineCycleJEPAModel,
    CosineJEPA,
    CosineJEPAModel,
    CycleJEPA,
    CycleJEPAModel,
    FlowLatentPredictor,
    FlowTSJEPA,
    FlowTSJEPAModel,
    HarmonicGrassmannianCodebook,
    HarmonicSpringHead,
    HarmonicSpringJEPA,
    HarmonicSpringJEPAModel,
    HarmonicStateSpaceCell,
    KoopmanJEPA,
    KoopmanJEPAModel,
    KoopmanOperatorPredictor,
    LatentPredictor,
    MultiScaleTSJEPA,
    NCADFlowJEPAModel,
    NCADJEPAModel,
    PatchFlowJEPA,
    PatchFlowPredictor,
    PatchTSJEPA,
    PotentialFlowJEPA,
    PotentialFlowJEPAModel,
    PotentialFlowPredictor,
    RecurrentKoopmanJEPA,
    RecurrentKoopmanJEPAModel,
    RecurrentSSMEncoder,
    RelationalGAT_JEPAModel,
    ScalarPotentialField,
    SpringJEPA,
    TSJEPAModel,
    TangentNormalJEPA,
    TangentNormalJEPAModel,
    TangentSubspaceHead,
    TangentHarmonicJEPA,
    TangentHarmonicJEPAModel,
    ReynoldsStressJEPA,
    ReynoldsStressJEPAModel,
    OperatorEntropyJEPA,
    OperatorEntropyJEPAModel,
    PrototypeGraphJEPA,
    PrototypeGraphJEPAModel,
    PrototypeGraphModule,
    TransferFunctionJEPA,
    TransferFunctionJEPAModel,
    MDLCompressorJEPA,
    MDLCompressorJEPAModel,
    GrangerCausalJEPA,
    GrangerCausalJEPAModel,
    HamiltonianSymplecticJEPA,
    HamiltonianSymplecticJEPAModel,
    LatentWorldJEPA,
    LatentWorldJEPAModel,
    SpatialFrameEncoder,
    LatentRecurrentCore,
    MultiScaleLatentWorldJEPA,
    MultiScaleLatentWorldJEPAModel,
    SelectiveLatentWorldJEPA,
    SelectiveLatentWorldJEPAModel,
    MemoryBankLatentWorldJEPA,
    MemoryBankLatentWorldJEPAModel,
    DualTimescaleLatentWorldJEPA,
    DualTimescaleLatentWorldJEPAModel,
    KinematicAdaptiveLatentJEPA,
    KinematicAdaptiveLatentJEPAModel,
    LatentDeliberationJEPA,
    LatentDeliberationJEPAModel,
    SpectralPhysicsLatentJEPA,
    SpectralPhysicsLatentJEPAModel,
    MultiAgentConsensusLatentJEPA,
    MultiAgentConsensusLatentJEPAModel,
    flow_matching_vicreg_loss,
    jepa_vicreg_loss,
    von_neumann_operator_entropy_loss,
)




from src.models.losses import (
    AnomalyInjectionConfig,
    ContextualAnomalyInjector,
    FrequencyMasker,
    sigreg_loss,
)
from src.models.memory import (
    CounterfactualSuccessorMemory,
    SuccessorMemoryConfig,
)

__all__ = [
    # Encoders
    "HybridTCNEncoder",
    "MultiScaleTCNEncoder",
    "RelationalGATEncoder",
    "SelectiveSSMContextEncoder",
    # Memory & Dynamics
    "CounterfactualSuccessorMemory",
    "SuccessorMemoryConfig",
    # JEPA & Invariance Architectures
    "TSJEPAModel",
    "PatchTSJEPA",
    "MultiScaleTSJEPA",
    "LatentPredictor",
    "NCADJEPAModel",
    "NCADFlowJEPAModel",
    "RelationalGAT_JEPAModel",
    "FrequencyMasker",
    # Flow-JEPA, Potential Flow, Harmonic Spring & Minimalist JEPAs
    "FlowTSJEPA",
    "FlowTSJEPAModel",
    "FlowLatentPredictor",
    "PotentialFlowJEPA",
    "PotentialFlowJEPAModel",
    "PF_JEPA",
    "PotentialFlowPredictor",
    "ScalarPotentialField",
    "HarmonicGrassmannianCodebook",
    "HarmonicSpringJEPA",
    "HarmonicSpringJEPAModel",
    "HarmonicSpringHead",
    "SpringJEPA",
    "CosineJEPA",
    "CosineJEPAModel",
    "CycleJEPA",
    "CycleJEPAModel",
    "CosineCycleJEPA",
    "CosineCycleJEPAModel",
    "KoopmanJEPA",
    "KoopmanJEPAModel",
    "KoopmanOperatorPredictor",
    "RecurrentKoopmanJEPA",
    "RecurrentKoopmanJEPAModel",
    "HarmonicStateSpaceCell",
    "RecurrentSSMEncoder",
    "TangentNormalJEPA",
    "TangentNormalJEPAModel",
    "TangentSubspaceHead",
    "TangentHarmonicJEPA",
    "TangentHarmonicJEPAModel",
    "ReynoldsStressJEPA",
    "ReynoldsStressJEPAModel",
    "OperatorEntropyJEPA",
    "OperatorEntropyJEPAModel",
    "PrototypeGraphJEPA",
    "PrototypeGraphJEPAModel",
    "PrototypeGraphModule",
    "TransferFunctionJEPA",
    "TransferFunctionJEPAModel",
    "MDLCompressorJEPA",
    "MDLCompressorJEPAModel",
    "GrangerCausalJEPA",
    "GrangerCausalJEPAModel",
    "HamiltonianSymplecticJEPA",
    "HamiltonianSymplecticJEPAModel",
    "LatentWorldJEPA",
    "LatentWorldJEPAModel",
    "SpatialFrameEncoder",
    "LatentRecurrentCore",
    "MultiScaleLatentWorldJEPA",
    "MultiScaleLatentWorldJEPAModel",
    "SelectiveLatentWorldJEPA",
    "SelectiveLatentWorldJEPAModel",
    "MemoryBankLatentWorldJEPA",
    "MemoryBankLatentWorldJEPAModel",
    "DualTimescaleLatentWorldJEPA",
    "DualTimescaleLatentWorldJEPAModel",
    "KinematicAdaptiveLatentJEPA",
    "KinematicAdaptiveLatentJEPAModel",
    "LatentDeliberationJEPA",
    "LatentDeliberationJEPAModel",
    "SpectralPhysicsLatentJEPA",
    "SpectralPhysicsLatentJEPAModel",
    "MultiAgentConsensusLatentJEPA",
    "MultiAgentConsensusLatentJEPAModel",
    "CausalSSMFlowJEPA",



    "CausalSSMContextEncoder",
    "flow_matching_vicreg_loss",
    "von_neumann_operator_entropy_loss",
    "PatchFlowJEPA",
    "PatchFlowPredictor",
    # SOTA Baselines


    "AnomalyTransformer",
    "DCdetector",
    "TimesNet",
    "TranAD",
    # Anomaly Injections & Losses
    "ContextualAnomalyInjector",
    "AnomalyInjectionConfig",
    "contrastive_loss",
    "jepa_vicreg_loss",
    "sigreg_loss",
]

